[10-Nov-2015 01:37:49 Europe/Berlin] PHP Fatal error:  Uncaught exception 'FastFood\Helper\RegexValidatorException' with message 'Preencha o campo nome' in P:\Dropbox\Integrado\TCC\api\module\FastFood\Helper\PostField.php:49
Stack trace:
#0 P:\Dropbox\Integrado\TCC\api\module\FastFood\Controller\ClienteController.php(227): FastFood\Helper\PostField->validate()
#1 P:\Dropbox\Integrado\TCC\api\module\FastFood\Controller\ClienteController.php(37): FastFood\Controller\ClienteController->doPostCliente('1')
#2 [internal function]: FastFood\Controller\ClienteController->indexAction('1')
#3 P:\Dropbox\Integrado\TCC\api\src\Szy\Mvc\Application.php(58): call_user_func_array(Array, Array)
#4 P:\Dropbox\Integrado\TCC\api\index.php(37): Szy\Mvc\Application->run(Object(Szy\Mvc\Route))
#5 {main}
  thrown in P:\Dropbox\Integrado\TCC\api\module\FastFood\Helper\PostField.php on line 49
[10-Nov-2015 01:37:54 Europe/Berlin] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Uma tentativa de conexão falhou porque o componente conectado não respondeu
corretamente após um período de tempo ou a conexão estabelecida falhou
porque o host conectado não respondeu.
' in P:\Dropbox\Integrado\TCC\api\src\Szy\Database\PDOConnection.php:24
Stack trace:
#0 P:\Dropbox\Integrado\TCC\api\src\Szy\Database\PDOConnection.php(24): PDO->__construct('mysql:host=mysq...', 'u366610268_food', 'masterkey')
#1 P:\Dropbox\Integrado\TCC\api\src\Szy\Mvc\Model\AbstractModel.php(24): Szy\Database\PDOConnection->__construct('mysql.hostinger...', 'u366610268_food', 'masterkey', 'u366610268_food')
#2 P:\Dropbox\Integrado\TCC\api\src\Szy\Mvc\Model\AbstractModel.php(83): Szy\Mvc\Model\AbstractModel->getConnection()
#3 P:\Dropbox\Integrado\TCC\api\module\FastFood\Model\ClienteModel.php(15): Szy\Mvc\Model\AbstractModel->query('SELECT * FROM c...', Array)
#4 P:\Dropbox\Integrado\TCC\api\module\FastFood\Controller\ClienteController.php(167): FastF in P:\Dropbox\Integrado\TCC\api\src\Szy\Database\PDOConnection.php on line 24
[10-Nov-2015 01:37:55 Europe/Berlin] PHP Fatal error:  Uncaught exception 'FastFood\Helper\RegexValidatorException' with message 'Preencha o campo nome' in P:\Dropbox\Integrado\TCC\api\module\FastFood\Helper\PostField.php:49
Stack trace:
#0 P:\Dropbox\Integrado\TCC\api\module\FastFood\Controller\ClienteController.php(227): FastFood\Helper\PostField->validate()
#1 P:\Dropbox\Integrado\TCC\api\module\FastFood\Controller\ClienteController.php(37): FastFood\Controller\ClienteController->doPostCliente('1')
#2 [internal function]: FastFood\Controller\ClienteController->indexAction('1')
#3 P:\Dropbox\Integrado\TCC\api\src\Szy\Mvc\Application.php(58): call_user_func_array(Array, Array)
#4 P:\Dropbox\Integrado\TCC\api\index.php(37): Szy\Mvc\Application->run(Object(Szy\Mvc\Route))
#5 {main}
  thrown in P:\Dropbox\Integrado\TCC\api\module\FastFood\Helper\PostField.php on line 49
[10-Nov-2015 01:38:02 Europe/Berlin] PHP Fatal error:  Uncaught exception 'FastFood\Helper\RegexValidatorException' with message 'Preencha o campo nome' in P:\Dropbox\Integrado\TCC\api\module\FastFood\Helper\PostField.php:49
Stack trace:
#0 P:\Dropbox\Integrado\TCC\api\module\FastFood\Controller\ClienteController.php(227): FastFood\Helper\PostField->validate()
#1 P:\Dropbox\Integrado\TCC\api\module\FastFood\Controller\ClienteController.php(37): FastFood\Controller\ClienteController->doPostCliente('1')
#2 [internal function]: FastFood\Controller\ClienteController->indexAction('1')
#3 P:\Dropbox\Integrado\TCC\api\src\Szy\Mvc\Application.php(58): call_user_func_array(Array, Array)
#4 P:\Dropbox\Integrado\TCC\api\index.php(37): Szy\Mvc\Application->run(Object(Szy\Mvc\Route))
#5 {main}
  thrown in P:\Dropbox\Integrado\TCC\api\module\FastFood\Helper\PostField.php on line 49
[10-Nov-2015 01:38:12 Europe/Berlin] PHP Warning:  PDO::__construct():  in P:\Dropbox\Integrado\TCC\api\src\Szy\Database\PDOConnection.php on line 24
[10-Nov-2015 01:38:12 Europe/Berlin] PHP Stack trace:
[10-Nov-2015 01:38:12 Europe/Berlin] PHP   1. {main}() P:\Dropbox\Integrado\TCC\api\index.php:0
[10-Nov-2015 01:38:12 Europe/Berlin] PHP   2. Szy\Mvc\Application->run() P:\Dropbox\Integrado\TCC\api\index.php:37
[10-Nov-2015 01:38:12 Europe/Berlin] PHP   3. call_user_func_array:{P:\Dropbox\Integrado\TCC\api\src\Szy\Mvc\Application.php:58}() P:\Dropbox\Integrado\TCC\api\src\Szy\Mvc\Application.php:58
[10-Nov-2015 01:38:12 Europe/Berlin] PHP   4. FastFood\Controller\ClienteController->indexAction() P:\Dropbox\Integrado\TCC\api\src\Szy\Mvc\Application.php:58
[10-Nov-2015 01:38:12 Europe/Berlin] PHP   5. FastFood\Controller\ClienteController->doGetCliente() P:\Dropbox\Integrado\TCC\api\module\FastFood\Controller\ClienteController.php:33
[10-Nov-2015 01:38:12 Europe/Berlin] PHP   6. FastFood\Model\ClienteModel->cliente() P:\Dropbox\Integrado\TCC\api\module\FastFood\Controller\ClienteController.php:167
[10-Nov-2015 01:38:12 Europe/Berlin] PHP   7. Szy\Mvc\Model\AbstractModel->query() P:\Dropbox\Integrado\TCC\api\module\FastFood\Model\ClienteModel.php:15
[10-Nov-2015 01:38:12 Europe/Berlin] PHP   8. Szy\Mvc\Model\AbstractModel->getConnection() P:\Dropbox\Integrado\TCC\api\src\Szy\Mvc\Model\AbstractModel.php:83
[10-Nov-2015 01:38:12 Europe/Berlin] PHP   9. Szy\Database\PDOConnection->__construct() P:\Dropbox\Integrado\TCC\api\src\Szy\Mvc\Model\AbstractModel.php:24
[10-Nov-2015 01:38:12 Europe/Berlin] PHP  10. PDO->__construct() P:\Dropbox\Integrado\TCC\api\src\Szy\Database\PDOConnection.php:24
[10-Nov-2015 01:38:12 Europe/Berlin] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Este host não é conhecido. ' in P:\Dropbox\Integrado\TCC\api\src\Szy\Database\PDOConnection.php:24
Stack trace:
#0 P:\Dropbox\Integrado\TCC\api\src\Szy\Database\PDOConnection.php(24): PDO->__construct('mysql:host=mysq...', 'u366610268_food', 'masterkey')
#1 P:\Dropbox\Integrado\TCC\api\src\Szy\Mvc\Model\AbstractModel.php(24): Szy\Database\PDOConnection->__construct('mysql.hostinger...', 'u366610268_food', 'masterkey', 'u366610268_food')
#2 P:\Dropbox\Integrado\TCC\api\src\Szy\Mvc\Model\AbstractModel.php(83): Szy\Mvc\Model\AbstractModel->getConnection()
#3 P:\Dropbox\Integrado\TCC\api\module\FastFood\Model\ClienteModel.php(15): Szy\Mvc\Model\AbstractModel->query('SELECT * FROM c...', Array)
#4 P:\Dropbox\Integrado\TCC\api\module\FastFood\Controller\ClienteController.php(167): FastFood\Model\ClienteModel->cliente('1')
#5 P:\Dropbox\Integrado\TCC\api\module\FastFood\Controller\ClienteController.ph in P:\Dropbox\Integrado\TCC\api\src\Szy\Database\PDOConnection.php on line 24
[10-Nov-2015 01:38:46 Europe/Berlin] PHP Warning:  PDO::__construct():  in P:\Dropbox\Integrado\TCC\api\src\Szy\Database\PDOConnection.php on line 24
[10-Nov-2015 01:38:46 Europe/Berlin] PHP Stack trace:
[10-Nov-2015 01:38:46 Europe/Berlin] PHP   1. {main}() P:\Dropbox\Integrado\TCC\api\index.php:0
[10-Nov-2015 01:38:46 Europe/Berlin] PHP   2. Szy\Mvc\Application->run() P:\Dropbox\Integrado\TCC\api\index.php:37
[10-Nov-2015 01:38:46 Europe/Berlin] PHP   3. call_user_func_array:{P:\Dropbox\Integrado\TCC\api\src\Szy\Mvc\Application.php:58}() P:\Dropbox\Integrado\TCC\api\src\Szy\Mvc\Application.php:58
[10-Nov-2015 01:38:46 Europe/Berlin] PHP   4. FastFood\Controller\ClienteController->indexAction() P:\Dropbox\Integrado\TCC\api\src\Szy\Mvc\Application.php:58
[10-Nov-2015 01:38:46 Europe/Berlin] PHP   5. FastFood\Controller\ClienteController->doGetCliente() P:\Dropbox\Integrado\TCC\api\module\FastFood\Controller\ClienteController.php:33
[10-Nov-2015 01:38:46 Europe/Berlin] PHP   6. FastFood\Model\ClienteModel->cliente() P:\Dropbox\Integrado\TCC\api\module\FastFood\Controller\ClienteController.php:167
[10-Nov-2015 01:38:46 Europe/Berlin] PHP   7. Szy\Mvc\Model\AbstractModel->query() P:\Dropbox\Integrado\TCC\api\module\FastFood\Model\ClienteModel.php:15
[10-Nov-2015 01:38:46 Europe/Berlin] PHP   8. Szy\Mvc\Model\AbstractModel->getConnection() P:\Dropbox\Integrado\TCC\api\src\Szy\Mvc\Model\AbstractModel.php:83
[10-Nov-2015 01:38:46 Europe/Berlin] PHP   9. Szy\Database\PDOConnection->__construct() P:\Dropbox\Integrado\TCC\api\src\Szy\Mvc\Model\AbstractModel.php:24
[10-Nov-2015 01:38:46 Europe/Berlin] PHP  10. PDO->__construct() P:\Dropbox\Integrado\TCC\api\src\Szy\Database\PDOConnection.php:24
[10-Nov-2015 01:38:46 Europe/Berlin] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Este host não é conhecido. ' in P:\Dropbox\Integrado\TCC\api\src\Szy\Database\PDOConnection.php:24
Stack trace:
#0 P:\Dropbox\Integrado\TCC\api\src\Szy\Database\PDOConnection.php(24): PDO->__construct('mysql:host=mysq...', 'u366610268_food', 'masterkey')
#1 P:\Dropbox\Integrado\TCC\api\src\Szy\Mvc\Model\AbstractModel.php(24): Szy\Database\PDOConnection->__construct('mysql.hostinger...', 'u366610268_food', 'masterkey', 'u366610268_food')
#2 P:\Dropbox\Integrado\TCC\api\src\Szy\Mvc\Model\AbstractModel.php(83): Szy\Mvc\Model\AbstractModel->getConnection()
#3 P:\Dropbox\Integrado\TCC\api\module\FastFood\Model\ClienteModel.php(15): Szy\Mvc\Model\AbstractModel->query('SELECT * FROM c...', Array)
#4 P:\Dropbox\Integrado\TCC\api\module\FastFood\Controller\ClienteController.php(167): FastFood\Model\ClienteModel->cliente('1')
#5 P:\Dropbox\Integrado\TCC\api\module\FastFood\Controller\ClienteController.ph in P:\Dropbox\Integrado\TCC\api\src\Szy\Database\PDOConnection.php on line 24
[10-Nov-2015 01:38:51 Europe/Berlin] PHP Warning:  PDO::__construct():  in P:\Dropbox\Integrado\TCC\api\src\Szy\Database\PDOConnection.php on line 24
[10-Nov-2015 01:38:51 Europe/Berlin] PHP Stack trace:
[10-Nov-2015 01:38:51 Europe/Berlin] PHP   1. {main}() P:\Dropbox\Integrado\TCC\api\index.php:0
[10-Nov-2015 01:38:51 Europe/Berlin] PHP   2. Szy\Mvc\Application->run() P:\Dropbox\Integrado\TCC\api\index.php:37
[10-Nov-2015 01:38:51 Europe/Berlin] PHP   3. call_user_func_array:{P:\Dropbox\Integrado\TCC\api\src\Szy\Mvc\Application.php:58}() P:\Dropbox\Integrado\TCC\api\src\Szy\Mvc\Application.php:58
[10-Nov-2015 01:38:51 Europe/Berlin] PHP   4. FastFood\Controller\ClienteController->indexAction() P:\Dropbox\Integrado\TCC\api\src\Szy\Mvc\Application.php:58
[10-Nov-2015 01:38:51 Europe/Berlin] PHP   5. FastFood\Controller\ClienteController->doGetCliente() P:\Dropbox\Integrado\TCC\api\module\FastFood\Controller\ClienteController.php:33
[10-Nov-2015 01:38:51 Europe/Berlin] PHP   6. FastFood\Model\ClienteModel->cliente() P:\Dropbox\Integrado\TCC\api\module\FastFood\Controller\ClienteController.php:167
[10-Nov-2015 01:38:51 Europe/Berlin] PHP   7. Szy\Mvc\Model\AbstractModel->query() P:\Dropbox\Integrado\TCC\api\module\FastFood\Model\ClienteModel.php:15
[10-Nov-2015 01:38:51 Europe/Berlin] PHP   8. Szy\Mvc\Model\AbstractModel->getConnection() P:\Dropbox\Integrado\TCC\api\src\Szy\Mvc\Model\AbstractModel.php:83
[10-Nov-2015 01:38:51 Europe/Berlin] PHP   9. Szy\Database\PDOConnection->__construct() P:\Dropbox\Integrado\TCC\api\src\Szy\Mvc\Model\AbstractModel.php:24
[10-Nov-2015 01:38:51 Europe/Berlin] PHP  10. PDO->__construct() P:\Dropbox\Integrado\TCC\api\src\Szy\Database\PDOConnection.php:24
[10-Nov-2015 01:38:51 Europe/Berlin] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Este host não é conhecido. ' in P:\Dropbox\Integrado\TCC\api\src\Szy\Database\PDOConnection.php:24
Stack trace:
#0 P:\Dropbox\Integrado\TCC\api\src\Szy\Database\PDOConnection.php(24): PDO->__construct('mysql:host=mysq...', 'u366610268_food', 'masterkey')
#1 P:\Dropbox\Integrado\TCC\api\src\Szy\Mvc\Model\AbstractModel.php(24): Szy\Database\PDOConnection->__construct('mysql.hostinger...', 'u366610268_food', 'masterkey', 'u366610268_food')
#2 P:\Dropbox\Integrado\TCC\api\src\Szy\Mvc\Model\AbstractModel.php(83): Szy\Mvc\Model\AbstractModel->getConnection()
#3 P:\Dropbox\Integrado\TCC\api\module\FastFood\Model\ClienteModel.php(15): Szy\Mvc\Model\AbstractModel->query('SELECT * FROM c...', Array)
#4 P:\Dropbox\Integrado\TCC\api\module\FastFood\Controller\ClienteController.php(167): FastFood\Model\ClienteModel->cliente('1')
#5 P:\Dropbox\Integrado\TCC\api\module\FastFood\Controller\ClienteController.ph in P:\Dropbox\Integrado\TCC\api\src\Szy\Database\PDOConnection.php on line 24
[10-Nov-2015 01:41:58 Europe/Berlin] PHP Notice:  Trying to get property of non-object in P:\Dropbox\Integrado\TCC\api\module\FastFood\Controller\PedidoController.php on line 24
[10-Nov-2015 01:41:58 Europe/Berlin] PHP Stack trace:
[10-Nov-2015 01:41:58 Europe/Berlin] PHP   1. {main}() P:\Dropbox\Integrado\TCC\api\index.php:0
[10-Nov-2015 01:41:58 Europe/Berlin] PHP   2. Szy\Mvc\Application->run() P:\Dropbox\Integrado\TCC\api\index.php:37
[10-Nov-2015 01:41:58 Europe/Berlin] PHP   3. call_user_func_array:{P:\Dropbox\Integrado\TCC\api\src\Szy\Mvc\Application.php:58}() P:\Dropbox\Integrado\TCC\api\src\Szy\Mvc\Application.php:58
[10-Nov-2015 01:41:58 Europe/Berlin] PHP   4. FastFood\Controller\PedidoController->indexAction() P:\Dropbox\Integrado\TCC\api\src\Szy\Mvc\Application.php:58
